// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('main');
x$.factory('color', function(){
  return {
    list: ['red', 'green', 'cyan', 'purple', 'magenta', 'black'],
    hash: {
      red: 0,
      green: 0,
      cyan: 0,
      purple: 0,
      magenta: 0,
      black: 0
    },
    total: function(v){
      return v.total = this.list.map(function(it){
        return parseInt(v[it]);
      }).reduce(function(a, b){
        return a + b;
      }, 0);
    }
  };
});
x$.filter('orderState', function(){
  return function(input){
    return ['建立中', '待付款', '已付款', '已出貨'][input];
  };
});
x$.controller('order', ['$scope', '$http', 'stateIndicator', '$timeout'].concat(function($scope, $http, stateIndicator, $timeout){
  $http.get('/api/order').success(function(d){
    return $scope.order = d;
  });
  return $scope.show = function(order){
    $scope.corder = order;
    return setTimeout(function(){
      return $('#detail').modal({
        show: true
      });
    }, 100);
  };
}));
x$.controller('sales', ['$scope', '$http', 'stateIndicator', '$timeout', 'color'].concat(function($scope, $http, stateIndicator, $timeout, color){
  return $http.get('/api/order').success(function(d){
    return [['init', 0], ['confirm', 1], ['paid', 2], ['shipped', 3]].map(function(v){
      var col, count, i$, len$, o, j$, ref$, len1$, k;
      col = d.filter(function(it){
        return it.state === v[1];
      });
      $scope[v[0]] = count = import$({}, color.hash);
      for (i$ = 0, len$ = col.length; i$ < len$; ++i$) {
        o = col[i$];
        for (j$ = 0, len1$ = (ref$ = color.list).length; j$ < len1$; ++j$) {
          k = ref$[j$];
          count[k] += o.info.count[k];
        }
      }
      return color.total(count);
    });
  });
}));
x$.controller('stock', ['$scope', '$http', 'stateIndicator', '$timeout', 'color'].concat(function($scope, $http, stateIndicator, $timeout, color){
  var x$;
  $scope.stock = {
    count: import$({}, color.hash),
    price: import$({}, color.hash)
  };
  x$ = $scope.state = stateIndicator.init();
  x$.loading();
  $http({
    url: "/api/stock",
    method: "GET"
  }).success(function(d){
    $scope.state.reset();
    $scope.stock = d;
    color.total($scope.stock.count);
    return console.log(d);
  });
  return $scope.update = function(){
    $scope.state.loading();
    color.total($scope.stock.count);
    return $http({
      url: "/api/stock",
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      data: JSON.stringify($scope.stock)
    }).success(function(d){
      return $timeout(function(){
        return $scope.state.done();
      }, 500);
    });
  };
}));
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}