// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('main');
x$.factory('allpay', function(){
  return {
    empty: {
      MerchantID: "2000132",
      MerchantTradeNo: "zbryikt123458",
      MerchantTradeDate: "2014/08/12 10:00:00",
      PaymentType: "aio",
      TotalAmount: "100",
      TradeDesc: "測試",
      ItemName: "testitem1",
      ReturnURL: "http://staging.fernwing.com/api/paidnotify",
      OrderResultURL: "http://staging.fernwing.com/api/order",
      ChoosePayment: "ALL",
      CheckMacValue: ""
    },
    hash: {
      key: "5294y06JbISpM5x9",
      iv: "v77hoKGq4kWxNNIS"
    },
    _encode: function(data){
      return data;
    },
    encode: function(data){
      var list, k, v, chk;
      list = [];
      for (k in data) {
        v = data[k];
        if (k === 'CheckMacValue') {
          continue;
        }
        list.push(k + "=" + v);
      }
      list.sort(function(a, b){
        a = a.toUpperCase();
        b = b.toUpperCase();
        if (a > b) {
          return 1;
        }
        if (a < b) {
          return -1;
        }
        return 0;
      });
      chk = list.join("&");
      if (this.hash.key) {
        chk = encodeURIComponent("HashKey=" + this.hash.key + "&" + chk + "&HashIV=" + this.hash.iv);
        chk = chk.replace(/%20/g, "+");
        chk = md5(chk.toLowerCase()).toUpperCase();
      } else {
        chk = this._encode(chk);
      }
      data.CheckMacValue = chk;
      return chk;
    }
  };
});
/*main = ($scope) ->
  $scope.data = do
    MerchantID: "2000132"
    MerchantTradeNo: "zbryikt123458"
    MerchantTradeDate: "2014/08/12 10:00:00"
    PaymentType: "aio"
    TotalAmount: "100"
    TradeDesc: "測試"
    ItemName: "testitem1"
    ReturnURL: "http://ec2-54-191-122-159.us-west-2.compute.amazonaws.com:9999/paidnotify"
    OrderResultURL: "http://ec2-54-191-122-159.us-west-2.compute.amazonaws.com:9999/order"
    ChoosePayment: "ALL"
    CheckMacValue: ""
  $scope.hash = do
    key: "5294y06JbISpM5x9"
    iv: "v77hoKGq4kWxNNIS"

  $scope.checkcode = ->
    list = []
    for k,v of $scope.data =>
      if k == 'CheckMacValue' => continue
      list.push "#k=#v"
    console.log list
    list.sort (a,b) -> 
      a = a.toUpperCase! 
      b = b.toUpperCase!
      if a > b => return 1
      if a < b => return -1
      return 0
    chk = list.join("&")
    chk = encodeURIComponent("HashKey=#{$scope.hash.key}&#chk&HashIV=#{$scope.hash.iv}")
    chk = chk.replace /%20/g, "+"
    chk = md5(chk.toLowerCase!).toUpperCase!
    $scope.data.CheckMacValue = chk
*/