// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('main');
x$.factory('dbref', function($firebase){
  return {
    ref: {},
    anf: {},
    data: {},
    update: function(data){
      var ret, item;
      ret = [];
      for (item in data) {
        if (item.indexOf("$") !== 0) {
          ret.push([item, data[item]]);
        }
      }
      return ret;
    },
    auth: function(app, cb){
      return new FirebaseSimpleLogin(new Firebase("https://" + app + ".firebaseio.com/"), cb);
    },
    get: function(app, path){
      var name, this$ = this;
      name = app + "//" + path;
      if (this.anf[name]) {
        return this.anf[name];
      }
      this.ref[name] = new Firebase("https://" + app + ".firebaseio.com/" + path);
      this.anf[name] = $firebase(this.ref[name]);
      this.anf[name].$on('loaded', function(v){
        return this$.data[name] = this$.update(v);
      });
      this.anf[name].$on('change', function(v){
        if (v) {
          return this$.data[name] = [[v, this$.anf[id][v]]].concat(this$.data[name] || []);
        }
      });
      return this.anf[name];
    }
    /*$scope.db = do
      order: db.get \fern, "user/$id/order"
      pending: db.get \fern, "admin/order/pending"
      count: db.get \fern, "count/$order"
    
    payload = $scope{name, email, addr, phone, count}
    $scope.db.order.$add payload
    $scope.db.count.$add {count: $scope.count, email: $scope.email}
    $scope.db.pending.$add {id: "???", email: $scope.email}*/
  };
});