// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('main');
x$.controller('login', ['$scope', '$http', '$timeout', '$location', 'stateIndicator', 'context'].concat(function($scope, $http, $timeout, $location, stateIndicator, context){
  $scope.user = context.user;
  $scope.state = stateIndicator.init();
  $scope.info = {
    email: "",
    passwd: ""
  };
  return $scope.login = function(url){
    $scope.state.loading();
    return $timeout(function(){
      return $http({
        url: '/d/login',
        method: 'POST',
        data: JSON.stringify($scope.info)
      }).success(function(d){
        $scope.state.done();
        $scope.user = d;
        $scope.fail = null;
        if (url) {
          return window.location.href = url;
        }
      }).error(function(e){
        $scope.state.fail();
        return $scope.fail = {
          detail: "login failed"
        };
      });
    }, 500);
  };
}));