// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('main');
x$.controller('login', ['$scope', '$http', 'stateIndicator', 'context'].concat(function($scope, $http, stateIndicator, context){
  $scope.user = context.user;
  $scope.state = stateIndicator.init();
  $scope.info = {
    username: "",
    password: ""
  };
  return $scope.login = function(){
    $scope.state.loading();
    return $http({
      url: '/d/login',
      method: 'POST',
      data: JSON.stringify($scope.info)
    }).success(function(d){
      $scope.state.done();
      $scope.user = d;
      return $scope.fail = null;
    }).error(function(e){
      $scope.state.done();
      return $scope.fail = {
        detail: "login failed"
      };
    });
  };
}));